import { DEFAULT_SHOP_PATH } from "@/lib/shop-url";
import type {
  MarketingServiceRecord,
  SiteSettingsBundle,
  TestimonialRecord,
} from "./types";

export const DEFAULT_SITE_SETTINGS: SiteSettingsBundle = {
  general: {
    organizationName: "IT Arena",
    defaultLocale: "sq",
    maintenanceMode: false,
    smtpNote: "SMTP is configured via environment variables.",
  },
  branding: {
    logoUrl: "",
    logoWhiteUrl: "",
    faviconUrl: "",
    primaryColor: "hsl(221, 83%, 53%)",
    accentColor: "hsl(38, 92%, 50%)",
    gradientFrom: "hsl(221, 83%, 53%)",
    gradientTo: "hsl(262, 83%, 58%)",
    fontFamily: "Inter",
    borderRadius: "0.75rem",
    buttonStyle: "gradient",
  },
  hero: {
    badge: {
      sq: "ISO 9001 & ISO 27001 Certified · Nga 2012",
      en: "ISO 9001 & ISO 27001 Certified · Since 2012",
    },
    titleLine1: { sq: "E Ardhmja", en: "Your" },
    titleHighlight: { sq: "Dixhitale", en: "Digital" },
    titleLine2: { sq: "Juaj", en: "Future" },
    subtitle: {
      sq: "Zgjidhje IT gjithëpërfshirëse për bizneset shqiptare — nga mbështetja ditore deri te transformimi dixhital. 500+ klientë na besojnë.",
      en: "Comprehensive IT solutions for Albanian businesses — from daily support to digital transformation. 500+ clients trust us.",
    },
    ctaPrimaryText: { sq: "Kërko Ofertë Falas", en: "Get Free Quote" },
    ctaPrimaryLink: "/kerko-oferte",
    ctaSecondaryText: { sq: "Vizito Dyqanin", en: "Visit Shop" },
    ctaSecondaryLink: DEFAULT_SHOP_PATH,
    ctaTertiaryText: { sq: "Shiko Shërbimet", en: "View Services" },
    ctaTertiaryLink: "#services",
    backgroundImageUrl: "",
    overlayOpacity: 0,
    gradientClass: "mesh-gradient",
    animation: "fade",
    quickStats: [
      { value: "500+", label: { sq: "Klientë", en: "Clients" }, iconKey: "Users" },
      { value: "12+", label: { sq: "Vite", en: "Years" }, iconKey: "Trophy" },
      { value: "24/7", label: { sq: "Mbështetje", en: "Support" }, iconKey: "Headphones" },
      { value: "98%", label: { sq: "Kënaqësi", en: "Satisfaction" }, iconKey: "TrendingUp" },
    ],
    bannerStats: [
      { value: "500+", label: { sq: "Klientë Aktivë", en: "Active Clients" }, iconKey: "Users" },
      { value: "12+", label: { sq: "Vite Eksperiencë", en: "Years Experience" }, iconKey: "Clock" },
      { value: "50+", label: { sq: "Inxhinierë Certifikuar", en: "Certified Engineers" }, iconKey: "Trophy" },
      { value: "24/7", label: { sq: "Mbështetje Teknike", en: "Tech Support" }, iconKey: "Zap" },
    ],
  },
  contact: {
    companyName: "IT Arena SH.P.K",
    email: "info@itarena.al",
    phone: "+355 69 63 14 319",
    address: {
      sq: "Rr. Loni Ligori, Astir\nTiranë, Shqipëri",
      en: "Loni Ligori St., Astir\nTirana, Albania",
    },
    mapsUrl: "https://maps.google.com",
    businessHours: {
      sq: "E Hënë–E Premte: 08:00–17:30\nE Shtunë: 08:00–13:00\n24/7 Emergjencë",
      en: "Mon–Fri: 08:00–17:30\nSat: 08:00–13:00\n24/7 Emergency",
    },
  },
  social: {
    links: [
      { network: "facebook", url: "https://facebook.com/itarena", enabled: true },
      { network: "instagram", url: "https://instagram.com/itarena", enabled: true },
      { network: "linkedin", url: "https://linkedin.com/company/itarena", enabled: true },
      { network: "whatsapp", url: "https://wa.me/355696314319", enabled: true },
    ],
  },
  footer: {
    description: {
      sq: "Partneri juaj strategjik teknologjik në Shqipëri. Nga 2012, duke fuqizuar mbi 500 biznese me zgjidhje IT të personalizuara.",
      en: "Your strategic technology partner in Albania. Since 2012, empowering 500+ businesses with tailored IT solutions.",
    },
    copyright: {
      sq: "© {year} IT Arena. Të gjitha të drejtat e rezervuara.",
      en: "© {year} IT Arena. All rights reserved.",
    },
    ctaText: { sq: "Kërko Ofertë", en: "Get a Quote" },
    ctaLink: "/kerko-oferte",
    links: [],
  },
  seo: {
    defaultTitle: {
      sq: "IT Arena — Zgjidhje IT për Biznese",
      en: "IT Arena — IT Solutions for Business",
    },
    defaultDescription: {
      sq: "Partneri juaj IT në Shqipëri: cloud, rrjet, CCTV, software dhe mbështetje 24/7.",
      en: "Your IT partner in Albania: cloud, networking, CCTV, software and 24/7 support.",
    },
    keywords: {
      sq: "IT, cloud, Microsoft 365, CCTV, rrjet, software, Tiranë",
      en: "IT, cloud, Microsoft 365, CCTV, networking, software, Tirana",
    },
    ogImageUrl: "",
  },
  landing: {
    sections: [
      { id: "hero", type: "hero", enabled: true, title: { sq: "Hero", en: "Hero" }, subtitle: { sq: "", en: "" }, background: "", animation: "fade" },
      { id: "stats", type: "stats", enabled: true, title: { sq: "Statistika", en: "Stats" }, subtitle: { sq: "", en: "" }, background: "", animation: "none" },
      { id: "services", type: "services", enabled: true, title: { sq: "Shërbimet", en: "Services" }, subtitle: { sq: "", en: "" }, background: "", animation: "fade" },
      { id: "industries", type: "industries", enabled: true, title: { sq: "Industri", en: "Industries" }, subtitle: { sq: "", en: "" }, background: "", animation: "none" },
      { id: "testimonials", type: "testimonials", enabled: true, title: { sq: "Dëshmi", en: "Testimonials" }, subtitle: { sq: "", en: "" }, background: "", animation: "fade" },
      { id: "cta", type: "cta", enabled: true, title: { sq: "CTA", en: "CTA" }, subtitle: { sq: "", en: "" }, background: "", animation: "none" },
    ],
    industries: [
      { name: { sq: "Kontabilitet", en: "Accounting" }, icon: "💼" },
      { name: { sq: "Ndërtim", en: "Construction" }, icon: "🏗️" },
      { name: { sq: "Arsim", en: "Education" }, icon: "🎓" },
      { name: { sq: "Inxhinieri", en: "Engineering" }, icon: "⚙️" },
      { name: { sq: "Imobiliare", en: "Real Estate" }, icon: "🏠" },
      { name: { sq: "Prodhim", en: "Manufacturing" }, icon: "🏭" },
      { name: { sq: "Shëndetësi", en: "Healthcare" }, icon: "🏥" },
      { name: { sq: "Hotele", en: "Hotels" }, icon: "🏨" },
      { name: { sq: "Zyra", en: "Offices" }, icon: "🏢" },
      { name: { sq: "Restorante", en: "Restaurants" }, icon: "🍽️" },
      { name: { sq: "Juridik", en: "Legal" }, icon: "⚖️" },
      { name: { sq: "Shitje me Pakicë", en: "Retail" }, icon: "🛍️" },
    ],
  },
};

export const DEFAULT_MARKETING_SERVICES: Omit<MarketingServiceRecord, "id">[] = [
  {
    slug: "it-support",
    sortOrder: 0,
    enabled: true,
    featured: true,
    nameSq: "IT Support & Helpdesk",
    nameEn: "IT Support & Helpdesk",
    shortDescSq: "Mbështetje teknike 24/7 me SLA të garantuara. Zgjidhim problemet tuaja IT brenda minutave, jo orëve.",
    shortDescEn: "24/7 technical support with guaranteed SLAs. We solve your IT problems in minutes, not hours.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Headphones",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: "Kërko ofertë",
    ctaTextEn: "Get a quote",
    ctaLink: "/kerko-oferte",
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-blue-600 to-blue-700",
    hoverEffect: null,
    colorClass: "bg-blue-50 text-blue-600 border-blue-100",
    accentClass: "from-blue-600 to-blue-700",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Ticket system prioritar", en: "Priority ticket system" },
      { sq: "Remote & onsite support", en: "Remote & onsite support" },
      { sq: "SLA 1-4 orë", en: "1-4h SLA" },
      { sq: "Menaxhim assetesh", en: "Asset management" },
    ],
  },
  {
    slug: "cloud",
    sortOrder: 1,
    enabled: true,
    featured: true,
    nameSq: "Cloud & Microsoft 365",
    nameEn: "Cloud & Microsoft 365",
    shortDescSq: "Migrimi, konfigurimi dhe menaxhimi i mjediseve cloud. Partner i çertifikuar Microsoft.",
    shortDescEn: "Migration, configuration and management of cloud environments. Certified Microsoft partner.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Cloud",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-sky-500 to-blue-600",
    hoverEffect: null,
    colorClass: "bg-sky-50 text-sky-600 border-sky-100",
    accentClass: "from-sky-500 to-blue-600",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Microsoft 365 / Azure", en: "Microsoft 365 / Azure" },
      { sq: "Cloud backup & DR", en: "Cloud backup & DR" },
      { sq: "Virtualizim (Hyper-V/VMware)", en: "Virtualization (Hyper-V/VMware)" },
      { sq: "Email profesional", en: "Professional email" },
    ],
  },
  {
    slug: "cctv-siguri",
    sortOrder: 2,
    enabled: true,
    featured: false,
    nameSq: "CCTV & Sisteme Sigurie",
    nameEn: "CCTV & Security Systems",
    shortDescSq: "Projektim dhe instalim i sistemeve CCTV, kontroll aksesi dhe sisteme alarmi. Partnerë Hikvision dhe Dahua.",
    shortDescEn: "Design and installation of CCTV, access control and alarm systems. Hikvision and Dahua partners.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Camera",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-rose-500 to-red-600",
    hoverEffect: null,
    colorClass: "bg-rose-50 text-rose-600 border-rose-100",
    accentClass: "from-rose-500 to-red-600",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "CCTV HD/4K/AI", en: "HD/4K/AI CCTV" },
      { sq: "Kontroll aksesi", en: "Access control" },
      { sq: "Alarme & detektim zjarri", en: "Alarms & fire detection" },
      { sq: "Monitorim në distancë", en: "Remote monitoring" },
    ],
  },
  {
    slug: "web-marketing",
    sortOrder: 3,
    enabled: true,
    featured: false,
    nameSq: "Web & Marketing Dixhital",
    nameEn: "Web & Digital Marketing",
    shortDescSq: "Zhvillim faqesh interneti, SEO, Google Ads dhe Social Media Marketing. Fitoni klientë të rinj online.",
    shortDescEn: "Website development, SEO, Google Ads and Social Media Marketing. Gain new clients online.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Globe",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-violet-600 to-purple-700",
    hoverEffect: null,
    colorClass: "bg-violet-50 text-violet-600 border-violet-100",
    accentClass: "from-violet-600 to-purple-700",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Faqe interneti profesionale", en: "Professional websites" },
      { sq: "SEO & Google Ads", en: "SEO & Google Ads" },
      { sq: "Social Media Management", en: "Social Media Management" },
      { sq: "Email marketing", en: "Email marketing" },
    ],
  },
  {
    slug: "rrjet",
    sortOrder: 4,
    enabled: true,
    featured: false,
    nameSq: "Rrjet & Infrastrukturë",
    nameEn: "Network & Infrastructure",
    shortDescSq: "Projektim, instalim dhe menaxhim i infrastrukturës së rrjetit — strukturuar dhe wireless.",
    shortDescEn: "Design, installation and management of network infrastructure — structured cabling and wireless.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Wifi",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-emerald-500 to-teal-600",
    hoverEffect: null,
    colorClass: "bg-emerald-50 text-emerald-600 border-emerald-100",
    accentClass: "from-emerald-500 to-teal-600",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Rrjet LAN/WAN/WiFi", en: "LAN/WAN/WiFi network" },
      { sq: "Kablim strukturor", en: "Structured cabling" },
      { sq: "Firewall & VPN", en: "Firewall & VPN" },
      { sq: "Monitorim 24/7", en: "24/7 monitoring" },
    ],
  },
  {
    slug: "software",
    sortOrder: 5,
    enabled: true,
    featured: false,
    nameSq: "Zhvillim Softuerësh",
    nameEn: "Software Development",
    shortDescSq: "Zhvillim i aplikacioneve web dhe mobile të personalizuara sipas nevojave specifike të biznesit tuaj.",
    shortDescEn: "Development of custom web and mobile applications tailored to your specific business needs.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Code2",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-amber-500 to-orange-600",
    hoverEffect: null,
    colorClass: "bg-amber-50 text-amber-600 border-amber-100",
    accentClass: "from-amber-500 to-orange-600",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Web apps (React/Next.js)", en: "Web apps (React/Next.js)" },
      { sq: "Mobile apps (iOS & Android)", en: "Mobile apps (iOS & Android)" },
      { sq: "API & integrime", en: "APIs & integrations" },
      { sq: "Mirëmbajtje & hosting", en: "Maintenance & hosting" },
    ],
  },
  {
    slug: "telekomunikacion",
    sortOrder: 6,
    enabled: true,
    featured: false,
    nameSq: "Telekomunikacion & VoIP",
    nameEn: "Telecommunications & VoIP",
    shortDescSq: "Sisteme telefonike IP, centrale VoIP dhe zgjidhje komunikimi të unifikuar për biznese.",
    shortDescEn: "IP phone systems, VoIP PBX, and unified communications solutions for businesses.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Phone",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-indigo-500 to-blue-600",
    hoverEffect: null,
    colorClass: "bg-indigo-50 text-indigo-600 border-indigo-100",
    accentClass: "from-indigo-500 to-blue-600",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Centrale VoIP (Asterisk/3CX)", en: "VoIP PBX (Asterisk/3CX)" },
      { sq: "IP Phones & video-konferencing", en: "IP phones & video conferencing" },
      { sq: "SIP trunking", en: "SIP trunking" },
      { sq: "Numra virtualë", en: "Virtual numbers" },
    ],
  },
  {
    slug: "printere",
    sortOrder: 7,
    enabled: true,
    featured: false,
    nameSq: "Printerë & Shërbime Printimi",
    nameEn: "Printers & Print Services",
    shortDescSq: "Shitje, instalim dhe mirëmbajtje e printerëve dhe fotokopjuesve. Kontrata mirëmbajtjeje me kosto fikse.",
    shortDescEn: "Sale, installation and maintenance of printers and copiers. Fixed-cost maintenance contracts.",
    fullDescSq: null,
    fullDescEn: null,
    iconKey: "Printer",
    imageUrl: null,
    bannerUrl: null,
    ctaTextSq: null,
    ctaTextEn: null,
    ctaLink: null,
    showOnHomepage: true,
    cardStyle: null,
    gradientClass: "from-orange-500 to-red-500",
    hoverEffect: null,
    colorClass: "bg-orange-50 text-orange-600 border-orange-100",
    accentClass: "from-orange-500 to-red-500",
    metaTitleSq: null,
    metaTitleEn: null,
    metaDescSq: null,
    metaDescEn: null,
    keywordsSq: null,
    keywordsEn: null,
    featuresJson: [
      { sq: "Printerë HP, Canon, Epson", en: "HP, Canon, Epson printers" },
      { sq: "MFP & fotokopjues", en: "MFP & copiers" },
      { sq: "Kontrata managed print", en: "Managed print contracts" },
      { sq: "Furnizim toner & letër", en: "Toner & paper supply" },
    ],
  },
];

export const DEFAULT_TESTIMONIALS: Omit<TestimonialRecord, "id">[] = [
  {
    sortOrder: 0,
    enabled: true,
    featured: true,
    clientName: "Arben Hoxha",
    roleSq: "CEO",
    roleEn: "CEO",
    companySq: "Biznes Partner",
    companyEn: "Business Partner",
    reviewSq:
      "IT Arena transformoi infrastrukturën tonë IT brenda 30 ditëve. Downtime zero, produktivitet i lartë. Rekomandoj me besim.",
    reviewEn:
      "IT Arena transformed our IT infrastructure within 30 days. Zero downtime, high productivity. I recommend them with confidence.",
    rating: 5,
    imageUrl: null,
    avatarColor: "bg-blue-500",
    initials: "AH",
  },
  {
    sortOrder: 1,
    enabled: true,
    featured: true,
    clientName: "Elona Krasniqi",
    roleSq: "CFO",
    roleEn: "CFO",
    companySq: null,
    companyEn: null,
    reviewSq:
      "Zgjidhja cloud dhe Microsoft 365 e implementuar nga IT Arena ul kostot tona operacionale me 40%. Ekip profesional dhe i dedikuar.",
    reviewEn:
      "The cloud and Microsoft 365 solution implemented by IT Arena reduced our operational costs by 40%. Professional and dedicated team.",
    rating: 5,
    imageUrl: null,
    avatarColor: "bg-emerald-500",
    initials: "EK",
  },
  {
    sortOrder: 2,
    enabled: true,
    featured: false,
    clientName: "Blerim Rexha",
    roleSq: "IT Manager",
    roleEn: "IT Manager",
    companySq: null,
    companyEn: null,
    reviewSq:
      "Kamera CCTV dhe sistemi i kontrollit të hyrjes punon pa defekt 24/7. Mbështetja e tyre është me të vërtetë 24 orë.",
    reviewEn:
      "CCTV cameras and the access control system work flawlessly 24/7. Their support is truly around the clock.",
    rating: 5,
    imageUrl: null,
    avatarColor: "bg-violet-500",
    initials: "BR",
  },
];
